[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pydistort"
url = "https://github.com/barsikus007/pydistort"
author = "barsikus007"
license = "MIT"
description = "Asynchronous media distortion module"
keywords = ["distort", "async"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
project_urls = { "Bug Tracker" = "https://github.com/barsikus007/pydistort/issues" }
dependencies  = [
    "apng",
    "lottie[GIF]",
]
python_requires = ">=3.10"
dynamic = ["version", "readme"]

[tool.setuptools.dynamic]
version = {attr = "pydistort.__version__"}
readme = {file = ["README.md"]}
#readme = {file = ["README.rst", "CHANGELOG.rst", "LICENSE.rst"]}
#packages = find:
