[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pydistort"
#url = "https://github.com/barsikus007/pydistort"
#author = "barsikus007"
description = "Asynchronous media distortion module"
keywords = ["distort", "async"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
#project_urls = { "Bug Tracker" = "https://github.com/barsikus007/pydistort/issues" }
dependencies  = [
    "apng",
    "lottie[GIF]",
]
#python_requires = ">=3.10"
dynamic = ["version", "readme"]

#[project.optional-dependencies]
#pdf = ["ReportLab>=1.2", "RXP"]
#rest = ["docutils>=0.3", "pack ==1.1, ==1.3"]

#[tool.setuptools.packages]
#find = {}  # Scan the project directory with the default parameters

[tool.setuptools.packages.find]
where = ["."]
#include = ["pkg*"]
#exclude = ["additional"]
#namespaces = false

[tool.setuptools.dynamic]
version = {attr = "pydistort.__version__"}
readme = {file = ["README.md", "LICENSE"]}
#readme = {file = ["README.rst", "CHANGELOG.rst", "LICENSE.rst"]}
